HOSTNAME='ftp.ncdc.noaa.gov'
HOURLY_PATH='/pub/data/uscrn/products/hourly02/'
DAILY_PATH='/pub/data/uscrn/products/daily01/'
MONTHLY_PATH='/pub/data/uscrn/products/monthly01/'
CREDENTIALS = ["ftp", "tomiger450\@dmonies.com"] # random email
STATIONS_TSV_LOCATION = "resources/stations.tsv"

XML_FILE_MAPPING={
    'hourly':'resources/weather-data-hourly.xml',
    'daily':'resources/weather-data-daily.xml',
    'monthly':'resources/weather-data-monthly.xml',
}

HEADER_HOURLY_MAPPING={
    'WBANNO':'station_number',
    'CRX_VN':'Version_Number_OF_Stations_Datalogger_Program',
    'UTC_DATE':'UTC_Date',
    'UTC_TIME':'UTC_Time',
    'LONGITUDE':'Longitude',
    'LATITUDE':'Latitude',
    'T_CALC':'Avg_Air_Temperature_Last_5_Min',
    'T_HR_AVG':'Avg_Air_Temperature',
    'T_MAX':'Max_Air_Temperature',
    'T_MIN':'Min_Air_Temperature',
    'P_CALC':'Precipitation',
    'SOLARAD':'Avg_Solar_Radioation',
    'SOLARAD_FLAG':'QC_Flag_Solar_Radioation_Avg',
    'SOLARAD_MAX':'Max_Solar_Radioation',
    'SOLARAD_MAX_FLAG':'QC_Flag_Solar_Radioation_Max',
    'SOLARAD_MIN':'Min_Solar_Radioation',
    'SOLARAD_MIN_FLAG':'QC_Flag_Solar_Radioation_Min',
    'SUR_TEMP_TYPE':'Infrared_Surface_Temperature_Type',
    'SUR_TEMP':'Avg_Infrared_Temperature',
    'SUR_TEMP_FLAG':'QC_Flag_Infrared_Surface_Temperature_Avg',
    'SUR_TEMP_MAX':'Max_Infrared_Temperature',
    'SUR_TEMP_MAX_FLAG':'QC_Flag_Infrared_Surface_Temperature_Max',
    'SUR_TEMP_MIN':'Min_Infrared_Temperature',
    'SUR_TEMP_MIN_FLAG':'QC_Flag_Infrared_Surface_Temperature_Min',
    'RH_HR_AVG':'Avg_RH',
    'RH_HR_AVG_FLAG':'QC_Flag_RH',
    'SOIL_MOISTURE_5':'Avg_Soil_Moisture_5_cm_below',
    'SOIL_MOISTURE_10':'Avg_Soil_Moisture_10_cm_below',
    'SOIL_MOISTURE_20':'Avg_Soil_Moisture_20_cm_below',
    'SOIL_MOISTURE_50':'Avg_Soil_Moisture_50_cm_below',
    'SOIL_MOISTURE_100':'Avg_Soil_Moisture_100_cm_below',
    'SOIL_TEMP_5':'Avg_Soil_Temperature_5_cm',
    'SOIL_TEMP_10':'Avg_Soil_Temperature_10_cm',
    'SOIL_TEMP_20':'Avg_Soil_Temperature_20_cm',
    'SOIL_TEMP_50':'Avg_Soil_Temperature_50_cm',
    'SOIL_TEMP_100':'Avg_Soil_Temperature_100_cm'
}
HEADER_DAILY_MAPPING={
    'WBANNO':'station_number',
    'CRX_VN':'Version_Number_OF_Stations_Datalogger_Program',
    'LST_DATE':'UTC_Date',
    'LONGITUDE':'Longitude',
    'LATITUDE':'Latitude',
    'T_DAILY_AVG':'Avg_Air_Temperature',
    'T_DAILY_MAX':'Max_Air_Temperature',
    'T_DAILY_MIN':'Min_Air_Temperature',
    'T_DAILY_MEAN':'Mean_Air_Temperature',
    'P_DAILY_CALC':'Precipitation',
    'SOLARAD_DAILY':'Total_Solar_Energy',
    'SUR_TEMP_DAILY_TYPE':'Infrared_Surface_Temperature_Type',
    'SUR_TEMP_DAILY_MAX':'Max_Infrared_Temperature',
    'SUR_TEMP_DAILY_MIN':'Min_Infrared_Temperature',
    'SUR_TEMP_DAILY_AVG':'Avg_Infrared_Temperature',
    'RH_DAILY_MAX':'Max_RH',
    'RH_DAILY_MIN':'Min_RH',
    'RH_DAILY_AVG':'Avg_RH',
    'SOIL_MOISTURE_5_DAILY':'Avg_Soil_Moisture_5_cm_below',
    'SOIL_MOISTURE_10_DAILY':'Avg_Soil_Moisture_10_cm_below',
    'SOIL_MOISTURE_20_DAILY':'Avg_Soil_Moisture_20_cm_below',
    'SOIL_MOISTURE_50_DAILY':'Avg_Soil_Moisture_50_cm_below',
    'SOIL_MOISTURE_100_DAILY':'Avg_Soil_Moisture_100_cm_below',
    'SOIL_TEMP_5_DAILY':'Avg_Soil_Temperature_5_cm',
    'SOIL_TEMP_10_DAILY':'Avg_Soil_Temperature_10_cm',
    'SOIL_TEMP_20_DAILY':'Avg_Soil_Temperature_20_cm',
    'SOIL_TEMP_50_DAILY':'Avg_Soil_Temperature_50_cm',
    'SOIL_TEMP_100_DAILY':'Avg_Soil_Temperature_100_cm'
}
HEADER_MONTHLY_MAPPING={
    'WBANNO':'station_number',
    'CRX_VN_MONTHLY':'Version_Number_OF_Stations_Datalogger_Program',
    'LST_YRMO':'UTC_Date',
    'PRECISE_LONGITUDE':'Longitude',
    'PRECISE_LATITUDE':'Latitude',
    'T_MONTHLY_AVG':'Avg_Air_Temperature',
    'T_MONTHLY_MAX':'Max_Air_Temperature',
    'T_MONTHLY_MIN':'Min_Air_Temperature',
    'T_MONTHLY_MEAN':'Mean_Air_Temperature',
    'P_MONTHLY_CALC':'Precipitation',
    'SOLRAD_MONTHLY_AVG':'Avg_Daily_Total_Solar_Energy',
    'SUR_TEMP_MONTHLY_TYPE':'Infrared_Surface_Temperature_Type',
    'SUR_TEMP_MONTHLY_MAX':'Max_Infrared_Temperature',
    'SUR_TEMP_MONTHLY_MIN':'Min_Infrared_Temperature',
    'SUR_TEMP_MONTHLY_AVG':'Avg_Infrared_Temperature'
}